FROM geopython/pygeoapi

ADD https://www.hydroshare.org/resource/47639953a95b40eb9af0f4972aac5c05/data/contents/nhd_centerlines.gpkg /data/nhd_centerlines.gpkg

ADD https://www.hydroshare.org/resource/47639953a95b40eb9af0f4972aac5c05/data/contents/insitu_chla.csv /data/insitu_chla.csv

ADD https://www.hydroshare.org/resource/47639953a95b40eb9af0f4972aac5c05/data/contents/rs_chla_predictions.csv /data/rs_chla_predictions.csv

COPY pygeoapi.config.yml /pygeoapi/local.config.yml
